---
- name: check configs
  shell: nginx -t
  register: nginx_config_status
  failed_when: nginx_config_status.rc == 1

- name: reload nginx
  systemd:
    name: 'nginx'
    state: reloaded
    daemon_reload: yes
    enabled: yes